version: '3.7'
services:
  app:
    depends_on:
      - db
    build:
      context: .
      dockerfile: app.Dockerfile
    ports:
      - target: 8080
        published: 80
    networks:
      netty:
  db:
    # environment:
    #   - MYSQL_ALLOW_EMPTY_PASSWORD=1
    build:
      context: .
      dockerfile: db.Dockerfile
    ports:
      - target: 3306
        published: 3306
    volumes:
      # volume is mounted to empty mysql datadir
      - type: volume
        source: data
        target: /var/lib/mysql
    networks:
      netty:
networks:
  netty:
volumes:
  data:

